FROM python:3.7
FROM nvcr.io/nvidia/pytorch:22.01-py3

WORKDIR /app
COPY . /app

# RUN /usr/local/bin/python -m pip install --upgrade pip
# RUN pip3 --default-timeout=5000 install -r requirements.txt
RUN pip install -r requirements.txt

CMD python manage.py

EXPOSE 8080