version: "2.3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: "kumagai_front"
    volumes:
      - "./:/app"
      - "/app/frontend/node_modules"
      - "/app/.vscode"
      - "/app/.idea"
    # 本番環境のサーバーで使用
    ports:
      - "80:80"
    depends_on:
      - uwsgi
    stdin_open: true

  postgres:
    image: postgres
    container_name: "postgres"
    volumes:
      - "database:/var/lib/postgresql/data"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=kumagai
    restart: always
    stdin_open: true


  # 本番環境のサーバーで使用
  uwsgi:
    build:
      context: .
      dockerfile: Dockerfile_uwsgi
    container_name: "uwsgi"
    volumes:
      - "./:/app"
      - "/app/.vscode"
      - "/app/.idea"
      # - "/app/nginx/work/nginx.conf"
    # expose:
    #   - "8080"
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      DATABASE_USER: root
      DATABASE_HOST: postgres
      DATABASE_PASSWORD: pass
      DATABASE_NAME: kumagai
    stdin_open: true
    tty: true
    depends_on:
      - postgres


volumes:
  database:
    driver: local